name: Pull Request Merge Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the pull request was merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "Pull request was not merged. Exiting..."
            exit 0
          fi

      # Add your desired steps here for the actions you want to perform after the pull request is merged
      - name: Example Step
        run: | 
            echo "This step runs after the pull request is merged"
            echo "Value of ${GITHUB_WORKSPACE} = "
            echo $GITHUB_WORKSPACE
