name: 'Publish JAR to Artifactory'

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the pull request was merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "Pull request was not merged. Exiting..."
            exit 0
          fi
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean jar
      - name: Print variables
        run: | 
            echo "This step runs after the pull request is merged"
            echo "Value of ${GITHUB_WORKSPACE} = "
            echo $GITHUB_WORKSPACE
