name: 'Publish JAR to Artifactory'

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: 'Your user for the Artifactory Repo'
        required: true
      password:
        description: 'Your password'
        required: true
  pull_request:
    types:
      - closed

jobs:
  build-deploy-plugin:
    runs-on: ubuntu-latest
    env:
      DOTCMS_ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USER }}
      DOTCMS_ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
    steps:
      - name: Check if the pull request was indeed merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "Pull request was not merged. Exiting..."
            exit 0
          fi
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Compiling code with Gradle Wrapper
        run: ./gradlew clean jar
      - name: Uploading JAR to Artifactory
        run: |
          echo "Input username = ${{ github.event.inputs.user_name }}"
          echo "Input password = ${{ github.event.inputs.password }}"
          USER_NAME = "${{ github.event.inputs.user_name }}"
          PASSWORD = "${{ github.event.inputs.password }}"
          if [[ -v ${USER_NAME} && -v ${PASSWORD}" ]]; then
            echo "User '${{ github.event.inputs.user_name }}' is manually publishing this plugin to Artifactory"
            export DOTCMS_ARTIFACTORY_USERNAME="${{ github.event.inputs.user_name }}"
            export DOTCMS_ARTIFACTORY_PASSWORD="${{ github.event.inputs.password }}"
          fi
          ./gradlew artifactoryPublish
